# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-23 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thirdparty_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csrs.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csrs.Feature')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csrs.Service')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.IntegerField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csrs.Feature')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csrs.Provider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csrs.Service')),
            ],
        ),
        migrations.AddField(
            model_name='providerservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csrs.Service'),
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together=set([('feature', 'id')]),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csrs.Feature'),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csrs.Provider'),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csrs.Service'),
        ),
    ]
